import 'dart:io';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart' show Share, XFile;
import 'package:intl/intl.dart';
import '../receipt.dart';
import '../models/trip.dart';
import 'analytics_service.dart';

class ReportService {
  static final _currency = NumberFormat.simpleCurrency();
  static final _dateFmt = DateFormat('MMM d, yyyy');

  static const _purple = PdfColor.fromInt(0xFF46166B);
  static const _gold = PdfColor.fromInt(0xFFE8A824);
  static const _darkText = PdfColor.fromInt(0xFF111827);
  static const _grayText = PdfColor.fromInt(0xFF6B7280);
  static const _lightBg = PdfColor.fromInt(0xFFFDF6E3);
  static const _borderColor = PdfColor.fromInt(0xFFE5E7EB);

  static const _categoryColors = <String, PdfColor>{
    'Ground Transportation': PdfColor.fromInt(0xFF46166B),
    'Meals': PdfColor.fromInt(0xFFE8A824),
    'Accommodation Cost': PdfColor.fromInt(0xFF7B3FA0),
    'Registration Cost': PdfColor.fromInt(0xFFD49B1F),
    'Flight Cost': PdfColor.fromInt(0xFF1565C0),
    'Other AS Cost': PdfColor.fromInt(0xFFB08D3A),
  };

  static const _categoryLabels = <String, String>{
    'Ground Transportation': 'Transportation',
    'Meals': 'Meals',
    'Accommodation Cost': 'Accommodation',
    'Registration Cost': 'Registration',
    'Flight Cost': 'Flight',
    'Other AS Cost': 'Other AS Cost',
  };

  /// Generate and share an expense report PDF.
  static Future<void> generateAndShare({
    required PeriodSnapshot data,
    required List<Receipt> receipts,
    required List<Trip> trips,
    required String periodLabel,
    required String periodType,
  }) async {
    final pdf = pw.Document();

    final bold = pw.Font.helveticaBold();
    final regular = pw.Font.helvetica();

    // Load logo
    pw.ImageProvider? logoImage;
    try {
      final logoBytes = await rootBundle.load('assets/asgo_logo.jpeg');
      logoImage = pw.MemoryImage(logoBytes.buffer.asUint8List());
    } catch (_) {
      // Logo not found, continue without it
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header with logo
          _buildHeader(periodLabel, periodType, bold, regular, logoImage),
          pw.SizedBox(height: 20),

          // Summary card
          _buildSummaryCard(data, bold, regular),
          pw.SizedBox(height: 20),

          // Payment method split
          _buildPaymentSplit(data, bold, regular),
          pw.SizedBox(height: 20),

          // Category breakdown
          _buildCategoryBreakdown(data, bold, regular),
          pw.SizedBox(height: 24),

          // Trips section
          _buildTripsSection(trips, bold, regular),
          if (trips.isNotEmpty) pw.SizedBox(height: 24),

          // Receipt table
          _buildReceiptTable(receipts, bold, regular),
        ],
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            'Generated by ASGo | Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(font: regular, fontSize: 8, color: _grayText),
          ),
        ),
      ),
    );

    final dir = await getTemporaryDirectory();
    final fileName = 'ASGo_${periodType}_Report_${periodLabel.replaceAll(' ', '_')}.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    // Don't await — let the share sheet open without blocking the caller
    Share.shareXFiles(
      [XFile(file.path)],
      subject: 'ASGo $periodType Report - $periodLabel',
    );
  }

  static pw.Widget _buildHeader(String periodLabel, String periodType, pw.Font bold, pw.Font regular, pw.ImageProvider? logo) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _purple,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        children: [
          if (logo != null) ...[
            pw.ClipRRect(
              horizontalRadius: 6,
              verticalRadius: 6,
              child: pw.Image(logo, width: 40, height: 40),
            ),
            pw.SizedBox(width: 12),
          ],
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('ASGo Expense Report', style: pw.TextStyle(font: bold, fontSize: 18, color: PdfColors.white)),
                pw.SizedBox(height: 4),
                pw.Text('$periodType Report | $periodLabel', style: pw.TextStyle(font: regular, fontSize: 10, color: const PdfColor.fromInt(0xFFD1C4E9))),
              ],
            ),
          ),
          pw.Text(_dateFmt.format(DateTime.now()), style: pw.TextStyle(font: regular, fontSize: 9, color: const PdfColor.fromInt(0xFFD1C4E9))),
        ],
      ),
    );
  }

  static pw.Widget _buildSummaryCard(PeriodSnapshot data, pw.Font bold, pw.Font regular) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _lightBg,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: _gold, width: 0.5),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('TOTAL SPENDING', style: pw.TextStyle(font: bold, fontSize: 9, color: _grayText, letterSpacing: 1)),
              pw.SizedBox(height: 4),
              pw.Text(_currency.format(data.total), style: pw.TextStyle(font: bold, fontSize: 22, color: _darkText)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('${data.receipts} receipts', style: pw.TextStyle(font: regular, fontSize: 10, color: _grayText)),
              pw.SizedBox(height: 4),
              if (data.changeLabel.isNotEmpty)
                pw.Container(
                  constraints: const pw.BoxConstraints(maxWidth: 200),
                  child: pw.Text(
                    data.changeLabel,
                    style: pw.TextStyle(font: regular, fontSize: 9, color: data.change >= 0 ? const PdfColor.fromInt(0xFFDC2626) : const PdfColor.fromInt(0xFF059669)),
                    textAlign: pw.TextAlign.right,
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildPaymentSplit(PeriodSnapshot data, pw.Font bold, pw.Font regular) {
    final total = data.personalTotal + data.amexTotal;
    final personalPct = total > 0 ? (data.personalTotal / total * 100).round() : 0;
    final amexPct = total > 0 ? (data.amexTotal / total * 100).round() : 0;

    return pw.Row(
      children: [
        pw.Expanded(child: _paymentBox('Personal', data.personalTotal, personalPct, _gold, bold, regular)),
        pw.SizedBox(width: 12),
        pw.Expanded(child: _paymentBox('AS Amex', data.amexTotal, amexPct, _purple, bold, regular)),
      ],
    );
  }

  static pw.Widget _paymentBox(String label, double amount, int pct, PdfColor color, pw.Font bold, pw.Font regular) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: _borderColor),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(children: [
            pw.Container(width: 8, height: 8, decoration: pw.BoxDecoration(color: color, shape: pw.BoxShape.circle)),
            pw.SizedBox(width: 6),
            pw.Text(label, style: pw.TextStyle(font: regular, fontSize: 9, color: _grayText)),
          ]),
          pw.SizedBox(height: 6),
          pw.Text(_currency.format(amount), style: pw.TextStyle(font: bold, fontSize: 14, color: _darkText)),
          pw.SizedBox(height: 4),
          pw.Text('$pct% of total', style: pw.TextStyle(font: regular, fontSize: 8, color: _grayText)),
        ],
      ),
    );
  }

  static pw.Widget _buildCategoryBreakdown(PeriodSnapshot data, pw.Font bold, pw.Font regular) {
    if (data.categories.isEmpty) return pw.SizedBox();

    final maxVal = data.categories.map((c) => c.amount).reduce((a, b) => a > b ? a : b);

    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: _borderColor),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('CATEGORY BREAKDOWN', style: pw.TextStyle(font: bold, fontSize: 9, color: _grayText, letterSpacing: 1)),
          pw.SizedBox(height: 12),
          ...data.categories.map((cat) {
            final color = _categoryColors[cat.name] ?? const PdfColor.fromInt(0xFFB08D3A);
            final label = _categoryLabels[cat.name] ?? cat.name;
            final fraction = maxVal > 0 ? cat.amount / maxVal : 0.0;
            final pct = data.total > 0 ? (cat.amount / data.total * 100).round() : 0;

            return pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 8),
              child: pw.Column(
                children: [
                  pw.Row(children: [
                    pw.Container(width: 8, height: 8, decoration: pw.BoxDecoration(color: color, shape: pw.BoxShape.circle)),
                    pw.SizedBox(width: 6),
                    pw.Expanded(child: pw.Text(label, style: pw.TextStyle(font: regular, fontSize: 10, color: _darkText))),
                    pw.Text(_currency.format(cat.amount), style: pw.TextStyle(font: bold, fontSize: 10, color: _darkText)),
                    pw.SizedBox(width: 6),
                    pw.Text('$pct%', style: pw.TextStyle(font: regular, fontSize: 8, color: _grayText)),
                  ]),
                  pw.SizedBox(height: 3),
                  pw.ClipRRect(
                    horizontalRadius: 3,
                    verticalRadius: 3,
                    child: pw.Stack(children: [
                      pw.Container(height: 4, color: const PdfColor.fromInt(0xFFF3F4F6)),
                      pw.Container(height: 4, width: fraction * 400, color: color),
                    ]),
                  ),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }

  static pw.Widget _buildTripsSection(List<Trip> trips, pw.Font bold, pw.Font regular) {
    if (trips.isEmpty) return pw.SizedBox();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('TRIPS', style: pw.TextStyle(font: bold, fontSize: 9, color: _grayText, letterSpacing: 1)),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(font: bold, fontSize: 9, color: PdfColors.white),
          headerDecoration: const pw.BoxDecoration(color: _purple),
          headerAlignment: pw.Alignment.centerLeft,
          cellStyle: pw.TextStyle(font: regular, fontSize: 8, color: _darkText),
          cellPadding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
          cellAlignments: {
            0: pw.Alignment.centerLeft,
            1: pw.Alignment.centerLeft,
            2: pw.Alignment.centerLeft,
            3: pw.Alignment.centerRight,
          },
          headers: ['Trip', 'Destination', 'Dates', 'Total Spent'],
          data: trips.map((t) {
            final dates = t.departureDate != null
                ? t.returnDate != null
                    ? '${_dateFmt.format(t.departureDate!)} - ${_dateFmt.format(t.returnDate!)}'
                    : _dateFmt.format(t.departureDate!)
                : '—';
            return [
              t.tripPurpose ?? 'Trip',
              t.destination ?? '—',
              dates,
              _currency.format(t.totalExpenses),
            ];
          }).toList(),
        ),
      ],
    );
  }

  static pw.Widget _buildReceiptTable(List<Receipt> receipts, pw.Font bold, pw.Font regular) {
    if (receipts.isEmpty) return pw.SizedBox();

    final sorted = List<Receipt>.from(receipts)..sort((a, b) {
      if (a.date == null && b.date == null) return 0;
      if (a.date == null) return 1;
      if (b.date == null) return -1;
      return a.date!.compareTo(b.date!);
    });

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('RECEIPT DETAILS', style: pw.TextStyle(font: bold, fontSize: 9, color: _grayText, letterSpacing: 1)),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(font: bold, fontSize: 9, color: PdfColors.white),
          headerDecoration: const pw.BoxDecoration(color: _purple),
          headerAlignment: pw.Alignment.centerLeft,
          cellStyle: pw.TextStyle(font: regular, fontSize: 8, color: _darkText),
          cellPadding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
          cellAlignments: {
            0: pw.Alignment.centerLeft,
            1: pw.Alignment.centerLeft,
            2: pw.Alignment.centerRight,
            3: pw.Alignment.centerLeft,
            4: pw.Alignment.centerLeft,
          },
          headers: ['Date', 'Merchant', 'Amount', 'Category', 'Payment'],
          data: sorted.map((r) => [
            r.date != null ? _dateFmt.format(r.date!) : '—',
            r.merchant ?? 'Unknown',
            _currency.format(r.effectiveTotal),
            _categoryLabels[r.travelCategory ?? r.category ?? ''] ?? r.travelCategory ?? r.category ?? '—',
            r.paymentMethod == 'corporate' ? 'AS Amex' : 'Personal',
          ]).toList(),
        ),
      ],
    );
  }
}
